# Generated by Django 4.2.1 on 2023-06-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
